%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NK_moreShocks';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(6,1);
M_.exo_names_tex = cell(6,1);
M_.exo_names_long = cell(6,1);
M_.exo_names(1) = {'epsA'};
M_.exo_names_tex(1) = {'{\epsilon^{A}}'};
M_.exo_names_long(1) = {'Labour augmenting shock'};
M_.exo_names(2) = {'epsG'};
M_.exo_names_tex(2) = {'{\epsilon^{G}}'};
M_.exo_names_long(2) = {'Government spending shock'};
M_.exo_names(3) = {'epsMS'};
M_.exo_names_tex(3) = {'{\epsilon^{MS}}'};
M_.exo_names_long(3) = {'Mark-up shock'};
M_.exo_names(4) = {'epsM'};
M_.exo_names_tex(4) = {'{\epsilon^{M}}'};
M_.exo_names_long(4) = {'Monetary policy shock'};
M_.exo_names(5) = {'epsIS'};
M_.exo_names_tex(5) = {'{\epsilon^{I}}}'};
M_.exo_names_long(5) = {'Investment Specific shock'};
M_.exo_names(6) = {'epsPS'};
M_.exo_names_tex(6) = {'{\epsilon^{U}}}'};
M_.exo_names_long(6) = {'Preference shock'};
M_.endo_names = cell(72,1);
M_.endo_names_tex = cell(72,1);
M_.endo_names_long = cell(72,1);
M_.endo_names(1) = {'U'};
M_.endo_names_tex(1) = {'U'};
M_.endo_names_long(1) = {'Utility'};
M_.endo_names(2) = {'UC'};
M_.endo_names_tex(2) = {'UC'};
M_.endo_names_long(2) = {'Marginal utility of consumption'};
M_.endo_names(3) = {'UH'};
M_.endo_names_tex(3) = {'UH'};
M_.endo_names_long(3) = {'Marginal utility of labour'};
M_.endo_names(4) = {'LAMBDA'};
M_.endo_names_tex(4) = {'\lambda'};
M_.endo_names_long(4) = {'Stochastic discount factor'};
M_.endo_names(5) = {'R'};
M_.endo_names_tex(5) = {'R'};
M_.endo_names_long(5) = {'Risk free interest rate'};
M_.endo_names(6) = {'RK'};
M_.endo_names_tex(6) = {'R^{K}'};
M_.endo_names_long(6) = {'Return on capital'};
M_.endo_names(7) = {'C'};
M_.endo_names_tex(7) = {'C'};
M_.endo_names_long(7) = {'Consumption'};
M_.endo_names(8) = {'W'};
M_.endo_names_tex(8) = {'W'};
M_.endo_names_long(8) = {'Real wage'};
M_.endo_names(9) = {'H'};
M_.endo_names_tex(9) = {'H'};
M_.endo_names_long(9) = {'Hours'};
M_.endo_names(10) = {'Y'};
M_.endo_names_tex(10) = {'Y'};
M_.endo_names_long(10) = {'Output'};
M_.endo_names(11) = {'PWP'};
M_.endo_names_tex(11) = {'P^{W}'};
M_.endo_names_long(11) = {'Intermediate price'};
M_.endo_names(12) = {'K'};
M_.endo_names_tex(12) = {'K'};
M_.endo_names_long(12) = {'Capital stock'};
M_.endo_names(13) = {'I'};
M_.endo_names_tex(13) = {'I'};
M_.endo_names_long(13) = {'Investment'};
M_.endo_names(14) = {'tax'};
M_.endo_names_tex(14) = {'Tax'};
M_.endo_names_long(14) = {'Taxes'};
M_.endo_names(15) = {'A'};
M_.endo_names_tex(15) = {'A'};
M_.endo_names_long(15) = {'Production technology'};
M_.endo_names(16) = {'G'};
M_.endo_names_tex(16) = {'G'};
M_.endo_names_long(16) = {'Government spending'};
M_.endo_names(17) = {'KY'};
M_.endo_names_tex(17) = {'\frac{\bar{K}}{\bar{YW}}'};
M_.endo_names_long(17) = {'Capital output ratio in steady state'};
M_.endo_names(18) = {'IY'};
M_.endo_names_tex(18) = {'\frac{\bar{I}}{\bar{Y}}'};
M_.endo_names_long(18) = {'Investment output ratio in steady state'};
M_.endo_names(19) = {'CY'};
M_.endo_names_tex(19) = {'\frac{\bar{C}}{\bar{Y}}'};
M_.endo_names_long(19) = {'Consumption output ratio in steady state'};
M_.endo_names(20) = {'S'};
M_.endo_names_tex(20) = {'S'};
M_.endo_names_long(20) = {'Investment adjustment costs'};
M_.endo_names(21) = {'Sdash'};
M_.endo_names_tex(21) = {'S^{l}'};
M_.endo_names_long(21) = {'Adjustment costs on X'};
M_.endo_names(22) = {'Q'};
M_.endo_names_tex(22) = {'Q'};
M_.endo_names_long(22) = {'Tobin Q'};
M_.endo_names(23) = {'X'};
M_.endo_names_tex(23) = {'X'};
M_.endo_names_long(23) = {'Gross growth rate of investment'};
M_.endo_names(24) = {'Rn'};
M_.endo_names_tex(24) = {'Rn'};
M_.endo_names_long(24) = {'Nominal interest rate'};
M_.endo_names(25) = {'ER'};
M_.endo_names_tex(25) = {'E(R)'};
M_.endo_names_long(25) = {'Ex-post real interest rate'};
M_.endo_names(26) = {'PIE'};
M_.endo_names_tex(26) = {'\pi'};
M_.endo_names_long(26) = {'Inflation'};
M_.endo_names(27) = {'MC'};
M_.endo_names_tex(27) = {'MC'};
M_.endo_names_long(27) = {'Real marginal costs'};
M_.endo_names(28) = {'JJ'};
M_.endo_names_tex(28) = {'JJ'};
M_.endo_names_long(28) = {'Price setting - Recursive auxiliary variable 1a'};
M_.endo_names(29) = {'JJtilde'};
M_.endo_names_tex(29) = {'\tilde{JJ}'};
M_.endo_names_long(29) = {'Price setting - Recursive auxiliary variable 2a'};
M_.endo_names(30) = {'J'};
M_.endo_names_tex(30) = {'J'};
M_.endo_names_long(30) = {'Price setting - Recursive auxiliary variable 1b'};
M_.endo_names(31) = {'Jtilde'};
M_.endo_names_tex(31) = {'\tilde{J}'};
M_.endo_names_long(31) = {'Price setting - Recursive auxiliary variable 2b'};
M_.endo_names(32) = {'PIEtilde'};
M_.endo_names_tex(32) = {'\tilde{\pi}'};
M_.endo_names_long(32) = {'Optimal reset price'};
M_.endo_names(33) = {'Delta'};
M_.endo_names_tex(33) = {'\delta'};
M_.endo_names_long(33) = {'Price dispersion'};
M_.endo_names(34) = {'MS'};
M_.endo_names_tex(34) = {'MS'};
M_.endo_names_long(34) = {'Mark-up shock'};
M_.endo_names(35) = {'UF'};
M_.endo_names_tex(35) = {'UF'};
M_.endo_names_long(35) = {'Utility - flexible prices'};
M_.endo_names(36) = {'UCF'};
M_.endo_names_tex(36) = {'UCF'};
M_.endo_names_long(36) = {'Marginal utility of consumption - flexible prices'};
M_.endo_names(37) = {'UHF'};
M_.endo_names_tex(37) = {'ULF'};
M_.endo_names_long(37) = {'Marginal utility of labour - flexible prices'};
M_.endo_names(38) = {'RF'};
M_.endo_names_tex(38) = {'RF'};
M_.endo_names_long(38) = {'Risk free interest rate - flexible prices'};
M_.endo_names(39) = {'GF'};
M_.endo_names_tex(39) = {'GF'};
M_.endo_names_long(39) = {'Government spending - flexible prices'};
M_.endo_names(40) = {'PWPF'};
M_.endo_names_tex(40) = {'PF^{W}'};
M_.endo_names_long(40) = {'Wholesale price - flxible prices'};
M_.endo_names(41) = {'HF'};
M_.endo_names_tex(41) = {'HF'};
M_.endo_names_long(41) = {'Hours - flxible prices'};
M_.endo_names(42) = {'YF'};
M_.endo_names_tex(42) = {'YF'};
M_.endo_names_long(42) = {'Output - flxible prices'};
M_.endo_names(43) = {'KF'};
M_.endo_names_tex(43) = {'KF'};
M_.endo_names_long(43) = {'Capital stock - flxible prices'};
M_.endo_names(44) = {'IF'};
M_.endo_names_tex(44) = {'IF'};
M_.endo_names_long(44) = {'Investment - flxible prices'};
M_.endo_names(45) = {'WF'};
M_.endo_names_tex(45) = {'WF'};
M_.endo_names_long(45) = {'Real wage - flxible prices'};
M_.endo_names(46) = {'CF'};
M_.endo_names_tex(46) = {'CF'};
M_.endo_names_long(46) = {'Consumption - flxible prices'};
M_.endo_names(47) = {'KYF'};
M_.endo_names_tex(47) = {'\frac{\bar{KF}}{\bar{YF}}'};
M_.endo_names_long(47) = {'Capital output ratio in steady state - flxible prices'};
M_.endo_names(48) = {'IYF'};
M_.endo_names_tex(48) = {'\frac{\bar{IF}}{\bar{YF}}'};
M_.endo_names_long(48) = {'Investment output ratio in steady state - flxible prices'};
M_.endo_names(49) = {'CYF'};
M_.endo_names_tex(49) = {'\frac{\bar{CF}}{\bar{YF}}'};
M_.endo_names_long(49) = {'Consumption output ratio in steady state - flxible prices'};
M_.endo_names(50) = {'taxF'};
M_.endo_names_tex(50) = {'TaxF'};
M_.endo_names_long(50) = {'Taxes - flxible prices'};
M_.endo_names(51) = {'LAMBDAF'};
M_.endo_names_tex(51) = {'\lambda'};
M_.endo_names_long(51) = {'Stochastic discount factor - flxible prices'};
M_.endo_names(52) = {'RKF'};
M_.endo_names_tex(52) = {'RFk'};
M_.endo_names_long(52) = {'Gross return on capital'};
M_.endo_names(53) = {'SF'};
M_.endo_names_tex(53) = {'SF'};
M_.endo_names_long(53) = {'Investment adjustment costs'};
M_.endo_names(54) = {'SdashF'};
M_.endo_names_tex(54) = {'SF^{l}'};
M_.endo_names_long(54) = {'Adjustment costs on X'};
M_.endo_names(55) = {'QF'};
M_.endo_names_tex(55) = {'QF'};
M_.endo_names_long(55) = {'Tobin Q'};
M_.endo_names(56) = {'XF'};
M_.endo_names_tex(56) = {'XF'};
M_.endo_names_long(56) = {'Gross growth rate of investment'};
M_.endo_names(57) = {'OUTGAP'};
M_.endo_names_tex(57) = {'OUTGAP'};
M_.endo_names_long(57) = {'Output gap'};
M_.endo_names(58) = {'IS'};
M_.endo_names_tex(58) = {'IS'};
M_.endo_names_long(58) = {'Investment Scaler'};
M_.endo_names(59) = {'PS'};
M_.endo_names_tex(59) = {'PS'};
M_.endo_names_long(59) = {'Preference Scaler'};
M_.endo_names(60) = {'RR'};
M_.endo_names_tex(60) = {'RR'};
M_.endo_names_long(60) = {'Real interest rate - deviation from the steady state'};
M_.endo_names(61) = {'RnRn'};
M_.endo_names_tex(61) = {'RRn'};
M_.endo_names_long(61) = {'Nominal interest rate - deviation from the steady state'};
M_.endo_names(62) = {'ERER'};
M_.endo_names_tex(62) = {'E(RR)'};
M_.endo_names_long(62) = {'Ex-post real interest rate - deviation from the steady state'};
M_.endo_names(63) = {'YY'};
M_.endo_names_tex(63) = {'yy'};
M_.endo_names_long(63) = {'Output - deviation from the steady state'};
M_.endo_names(64) = {'CC'};
M_.endo_names_tex(64) = {'cc'};
M_.endo_names_long(64) = {'Consumption - deviation from the steady state'};
M_.endo_names(65) = {'HH'};
M_.endo_names_tex(65) = {'hh'};
M_.endo_names_long(65) = {'Hours - deviation from the steady state'};
M_.endo_names(66) = {'WW'};
M_.endo_names_tex(66) = {'ww'};
M_.endo_names_long(66) = {'Real wage - deviation from the steady state'};
M_.endo_names(67) = {'II'};
M_.endo_names_tex(67) = {'ii'};
M_.endo_names_long(67) = {'Investment - deviation from the steady state'};
M_.endo_names(68) = {'KK'};
M_.endo_names_tex(68) = {'kk'};
M_.endo_names_long(68) = {'Capital - deviation from the steady state'};
M_.endo_names(69) = {'QQ'};
M_.endo_names_tex(69) = {'qq'};
M_.endo_names_long(69) = {'Tobin Q - deviation from the steady state'};
M_.endo_names(70) = {'PIEPIE'};
M_.endo_names_tex(70) = {'\pi\pi'};
M_.endo_names_long(70) = {'Inflation - deviation from the steady state'};
M_.endo_names(71) = {'OUTGAPOUTGAP'};
M_.endo_names_tex(71) = {'Ogapogap'};
M_.endo_names_long(71) = {'Output gap - deviation from the steady state'};
M_.endo_names(72) = {'varrho'};
M_.endo_names_tex(72) = {'{\varrho}'};
M_.endo_names_long(72) = {'Weight on Leisure in utility'};
M_.endo_partitions = struct();
M_.param_names = cell(26,1);
M_.param_names_tex = cell(26,1);
M_.param_names_long = cell(26,1);
M_.param_names(1) = {'gy'};
M_.param_names_tex(1) = {'{gy}'};
M_.param_names_long(1) = {'Government spending output ratio in steady state'};
M_.param_names(2) = {'zzeta'};
M_.param_names_tex(2) = {'{\zeta}'};
M_.param_names_long(2) = {'Elasticity of substitution across products'};
M_.param_names(3) = {'alp'};
M_.param_names_tex(3) = {'{\alpha}'};
M_.param_names_long(3) = {'Labour share'};
M_.param_names(4) = {'betta'};
M_.param_names_tex(4) = {'{\beta}'};
M_.param_names_long(4) = {'Discount factor'};
M_.param_names(5) = {'delta'};
M_.param_names_tex(5) = {'{\delta}'};
M_.param_names_long(5) = {'Capital depreciation'};
M_.param_names(6) = {'sigma_c'};
M_.param_names_tex(6) = {'{\sigma_{C}}'};
M_.param_names_long(6) = {'Inverse of the elasticity of substitution'};
M_.param_names(7) = {'rhoA'};
M_.param_names_tex(7) = {'{\rho_{A}}'};
M_.param_names_long(7) = {'Persistence of labour augmentig shock'};
M_.param_names(8) = {'rhoG'};
M_.param_names_tex(8) = {'{\rho_{G}}'};
M_.param_names_long(8) = {'Persistence of government spending shock'};
M_.param_names(9) = {'Ass'};
M_.param_names_tex(9) = {'{\bar{A}}'};
M_.param_names_long(9) = {'Labour technology in steady state'};
M_.param_names(10) = {'phiX'};
M_.param_names_tex(10) = {'{\phi_{X}}'};
M_.param_names_long(10) = {'Smoothing parameter of investment adjustment costs'};
M_.param_names(11) = {'xi'};
M_.param_names_tex(11) = {'{\xi}'};
M_.param_names_long(11) = {'Calvo parameter'};
M_.param_names(12) = {'rho_r'};
M_.param_names_tex(12) = {'{\rho_{R}}'};
M_.param_names_long(12) = {'Interest rate smoothing parameter'};
M_.param_names(13) = {'theta_pie'};
M_.param_names_tex(13) = {'\theta^{\pi}'};
M_.param_names_long(13) = {'Taylor rule parameter for inflation'};
M_.param_names(14) = {'theta_y'};
M_.param_names_tex(14) = {'\theta^{y}'};
M_.param_names_long(14) = {'Taylor rule parameter for output'};
M_.param_names(15) = {'rhoMS'};
M_.param_names_tex(15) = {'{\rho_{MS}}'};
M_.param_names_long(15) = {'Persistence of mark-up shock'};
M_.param_names(16) = {'chi'};
M_.param_names_tex(16) = {'{\chi}'};
M_.param_names_long(16) = {'habits persistence'};
M_.param_names(17) = {'gammap'};
M_.param_names_tex(17) = {'{\gamma^{p}}'};
M_.param_names_long(17) = {'degree of indexation'};
M_.param_names(18) = {'Hss'};
M_.param_names_tex(18) = {'{\bar{H}}'};
M_.param_names_long(18) = {'Hours in steady state'};
M_.param_names(19) = {'rhoPS'};
M_.param_names_tex(19) = {'{\rho_{U}}'};
M_.param_names_long(19) = {'Persistence of preference shock'};
M_.param_names(20) = {'rhoIS'};
M_.param_names_tex(20) = {'{\rho_{I}}'};
M_.param_names_long(20) = {'Persistence of investment shock'};
M_.param_names(21) = {'sigma_A'};
M_.param_names_tex(21) = {'{\sigma_{A}}'};
M_.param_names_long(21) = {'STD of labour augmentig shock'};
M_.param_names(22) = {'sigma_G'};
M_.param_names_tex(22) = {'{\sigma_{G}}'};
M_.param_names_long(22) = {'STD of government spendng shock'};
M_.param_names(23) = {'sigma_MS'};
M_.param_names_tex(23) = {'{\sigma_{MS}}'};
M_.param_names_long(23) = {'STD of mark-up shock'};
M_.param_names(24) = {'sigma_M'};
M_.param_names_tex(24) = {'{\sigma_{M}}'};
M_.param_names_long(24) = {'STD of monetary policy shock'};
M_.param_names(25) = {'sigma_PS'};
M_.param_names_tex(25) = {'{\sigma_{U}}'};
M_.param_names_long(25) = {'STD of preference shock'};
M_.param_names(26) = {'sigma_IS'};
M_.param_names_tex(26) = {'{\sigma_{I}}'};
M_.param_names_long(26) = {'STD of investment shock'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 6;
M_.endo_nbr = 72;
M_.param_nbr = 26;
M_.orig_endo_nbr = 72;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(6, 6);
M_.Correlation_matrix = eye(6, 6);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 72;
M_.eq_nbr = 72;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 20 0;
 1 21 0;
 0 22 0;
 0 23 92;
 0 24 93;
 0 25 94;
 2 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 3 31 0;
 4 32 0;
 0 33 0;
 5 34 0;
 6 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 95;
 7 41 96;
 0 42 97;
 8 43 0;
 0 44 0;
 9 45 98;
 0 46 0;
 0 47 0;
 0 48 99;
 0 49 0;
 0 50 100;
 0 51 0;
 10 52 0;
 11 53 0;
 0 54 0;
 12 55 0;
 0 56 0;
 0 57 0;
 13 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 14 62 0;
 15 63 0;
 0 64 0;
 16 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 101;
 0 71 102;
 0 72 0;
 0 73 103;
 17 74 104;
 0 75 105;
 0 76 0;
 18 77 0;
 19 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 0;
 0 91 0;]';
M_.nstatic = 42;
M_.nfwrd   = 11;
M_.npred   = 16;
M_.nboth   = 3;
M_.nsfwrd   = 14;
M_.nspred   = 19;
M_.ndynamic   = 30;
M_.dynamic_tmp_nbr = [31; 15; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Parameter varrho' ;
  2 , 'name' , 'Single period utility' ;
  3 , 'name' , 'Marginal Utility of Consumption (with external habits)' ;
  4 , 'name' , 'Marginal Utility of Labour (with external habits)' ;
  5 , 'name' , 'Stochastic discount factor - 1' ;
  6 , 'name' , 'Stochastic discount factor - 2' ;
  7 , 'name' , 'Fisher equation - real interest rate' ;
  8 , 'name' , 'Fisher equation - expected real interest rate' ;
  9 , 'name' , 'Labour Supply FOC' ;
  10 , 'name' , 'Price dispertion - eq. 10' ;
  11 , 'name' , 'Prodution function' ;
  12 , 'name' , 'Wholesale firms FOC - 1a' ;
  13 , 'name' , 'Wholesale firms FOC - 1b' ;
  14 , 'name' , 'Wholesale firms FOC - 2' ;
  15 , 'name' , 'Wholesale firms FOC - 3' ;
  16 , 'name' , 'Resource constraint' ;
  17 , 'name' , 'Capital law of motion' ;
  18 , 'name' , 'Gross growth rate of investment' ;
  19 , 'name' , 'Investment adjustment cost - 1' ;
  20 , 'name' , 'Investment adjustment cost - 2' ;
  21 , 'name' , 'Balanced budget constraint' ;
  22 , 'name' , 'Inflation dynamic - 1' ;
  23 , 'name' , 'Inflation dynamic - 2' ;
  24 , 'name' , 'Inflation dynamic - 3' ;
  25 , 'name' , 'Inflation dynamic - 4' ;
  26 , 'name' , 'Inflation dynamic - 5' ;
  27 , 'name' , 'Inflation dynamic - 6' ;
  28 , 'name' , 'Taylor rule - implementable rule (relative to ss)' ;
  29 , 'name' , 'Mark-up Monopolistic pricing' ;
  30 , 'name' , 'Labour augmenting shock process' ;
  31 , 'name' , 'Government shock process' ;
  32 , 'name' , 'Government shock process - flexible prices' ;
  33 , 'name' , 'Markup shock' ;
  34 , 'name' , 'Preference shock' ;
  35 , 'name' , 'Investment shock' ;
  36 , 'name' , 'YY' ;
  37 , 'name' , 'KK' ;
  38 , 'name' , 'II' ;
  39 , 'name' , 'CC' ;
  40 , 'name' , 'WW' ;
  41 , 'name' , 'HH' ;
  42 , 'name' , 'QQ' ;
  43 , 'name' , 'RR' ;
  44 , 'name' , 'ERER' ;
  45 , 'name' , 'RnRn' ;
  46 , 'name' , 'PIEPIE' ;
  47 , 'name' , 'OUTGAPOUTGAP' ;
  48 , 'name' , 'KY' ;
  49 , 'name' , 'IY' ;
  50 , 'name' , 'CY' ;
  51 , 'name' , 'Single period utility' ;
  52 , 'name' , 'Marginal Utility of Consumption (with external habits)' ;
  53 , 'name' , 'Marginal Utility of Labour (with external habits)' ;
  54 , 'name' , 'LAMBDAF' ;
  55 , 'name' , 'Stochastic Discount Factor - 2' ;
  56 , 'name' , 'Labour supply foc - eq 54' ;
  57 , 'name' , 'Prodution function' ;
  58 , 'name' , 'Wholesale firms FOC - 1a' ;
  59 , 'name' , 'Wholesale firms FOC - 1b' ;
  60 , 'name' , 'Wholesale firms FOC - 2' ;
  61 , 'name' , 'Wholesale firms FOC - 3' ;
  62 , 'name' , 'Resource constraint - eq 58' ;
  63 , 'name' , 'Capital law of motion' ;
  64 , 'name' , 'Gross growth rate of investment' ;
  65 , 'name' , 'Investment adjustment cost - 1' ;
  66 , 'name' , 'Investment adjustment cost - 2' ;
  67 , 'name' , 'Balance budget constraint' ;
  68 , 'name' , 'Mark-up monopolistic shock' ;
  69 , 'name' , 'Output gap' ;
  70 , 'name' , 'KYF' ;
  71 , 'name' , 'IYF' ;
  72 , 'name' , 'CYF' ;
};
M_.mapping.U.eqidx = [2 ];
M_.mapping.UC.eqidx = [3 5 9 22 23 ];
M_.mapping.UH.eqidx = [4 9 ];
M_.mapping.LAMBDA.eqidx = [5 6 13 14 ];
M_.mapping.R.eqidx = [6 7 43 ];
M_.mapping.RK.eqidx = [12 14 ];
M_.mapping.C.eqidx = [2 3 4 16 39 50 ];
M_.mapping.W.eqidx = [9 15 40 ];
M_.mapping.H.eqidx = [2 3 4 11 15 41 ];
M_.mapping.Y.eqidx = [11 12 15 16 22 23 28 36 48 49 50 69 ];
M_.mapping.PWP.eqidx = [12 15 29 ];
M_.mapping.K.eqidx = [11 12 17 37 48 ];
M_.mapping.I.eqidx = [16 17 18 38 49 ];
M_.mapping.tax.eqidx = [21 ];
M_.mapping.A.eqidx = [11 30 57 ];
M_.mapping.G.eqidx = [16 21 31 ];
M_.mapping.KY.eqidx = [48 ];
M_.mapping.IY.eqidx = [49 ];
M_.mapping.CY.eqidx = [50 ];
M_.mapping.S.eqidx = [13 17 19 ];
M_.mapping.Sdash.eqidx = [13 20 ];
M_.mapping.Q.eqidx = [12 13 42 ];
M_.mapping.X.eqidx = [13 18 19 20 ];
M_.mapping.Rn.eqidx = [7 8 28 45 ];
M_.mapping.ER.eqidx = [8 44 ];
M_.mapping.PIE.eqidx = [7 8 27 28 46 ];
M_.mapping.MC.eqidx = [23 29 ];
M_.mapping.JJ.eqidx = [10 22 24 26 ];
M_.mapping.JJtilde.eqidx = [22 24 ];
M_.mapping.J.eqidx = [10 23 25 26 ];
M_.mapping.Jtilde.eqidx = [23 25 ];
M_.mapping.PIEtilde.eqidx = [10 24 25 26 27 ];
M_.mapping.Delta.eqidx = [10 11 12 15 ];
M_.mapping.MS.eqidx = [23 33 ];
M_.mapping.UF.eqidx = [51 ];
M_.mapping.UCF.eqidx = [52 54 56 ];
M_.mapping.UHF.eqidx = [53 56 ];
M_.mapping.RF.eqidx = [55 ];
M_.mapping.GF.eqidx = [32 62 67 ];
M_.mapping.PWPF.eqidx = [58 61 68 ];
M_.mapping.HF.eqidx = [51 52 53 57 61 ];
M_.mapping.YF.eqidx = [57 58 61 62 69 70 71 72 ];
M_.mapping.KF.eqidx = [57 58 63 70 ];
M_.mapping.IF.eqidx = [62 63 64 71 ];
M_.mapping.WF.eqidx = [56 61 ];
M_.mapping.CF.eqidx = [51 52 53 62 72 ];
M_.mapping.KYF.eqidx = [70 ];
M_.mapping.IYF.eqidx = [71 ];
M_.mapping.CYF.eqidx = [72 ];
M_.mapping.taxF.eqidx = [67 ];
M_.mapping.LAMBDAF.eqidx = [54 55 59 60 ];
M_.mapping.RKF.eqidx = [58 60 ];
M_.mapping.SF.eqidx = [59 63 65 ];
M_.mapping.SdashF.eqidx = [59 66 ];
M_.mapping.QF.eqidx = [58 59 ];
M_.mapping.XF.eqidx = [59 64 65 66 ];
M_.mapping.OUTGAP.eqidx = [47 69 ];
M_.mapping.IS.eqidx = [17 35 ];
M_.mapping.PS.eqidx = [2 3 4 34 ];
M_.mapping.RR.eqidx = [43 ];
M_.mapping.RnRn.eqidx = [45 ];
M_.mapping.ERER.eqidx = [44 ];
M_.mapping.YY.eqidx = [36 ];
M_.mapping.CC.eqidx = [39 ];
M_.mapping.HH.eqidx = [41 ];
M_.mapping.WW.eqidx = [40 ];
M_.mapping.II.eqidx = [38 ];
M_.mapping.KK.eqidx = [37 ];
M_.mapping.QQ.eqidx = [42 ];
M_.mapping.PIEPIE.eqidx = [46 ];
M_.mapping.OUTGAPOUTGAP.eqidx = [47 ];
M_.mapping.varrho.eqidx = [1 2 3 4 51 52 53 ];
M_.mapping.epsA.eqidx = [30 ];
M_.mapping.epsG.eqidx = [31 32 ];
M_.mapping.epsMS.eqidx = [33 ];
M_.mapping.epsM.eqidx = [28 ];
M_.mapping.epsIS.eqidx = [35 ];
M_.mapping.epsPS.eqidx = [34 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 7 12 13 15 16 22 24 26 33 34 36 39 43 44 46 55 58 59 ];
M_.exo_names_orig_ord = [1:6];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(72, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(6, 1);
M_.params = NaN(26, 1);
M_.endo_trends = struct('deflator', cell(72, 1), 'log_deflator', cell(72, 1), 'growth_factor', cell(72, 1), 'log_growth_factor', cell(72, 1));
M_.NNZDerivatives = [240; -1; -1; ];
M_.static_tmp_nbr = [31; 16; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
close all;
debug;
M_.params(17) = 0.5;
gammap = M_.params(17);
M_.params(16) = 0.7;
chi = M_.params(16);
M_.params(18) = 0.35;
Hss = M_.params(18);
M_.params(10) = 4.0;
phiX = M_.params(10);
M_.params(1) = 0.2;
gy = M_.params(1);
M_.params(3) = 0.70;
alp = M_.params(3);
M_.params(2) = 7.0;
zzeta = M_.params(2);
M_.params(4) = 0.99;
betta = M_.params(4);
M_.params(5) = 0.0250;
delta = M_.params(5);
M_.params(6) = 2.0;
sigma_c = M_.params(6);
M_.params(12) = 0.7;
rho_r = M_.params(12);
M_.params(13) = 1.5;
theta_pie = M_.params(13);
M_.params(14) = 0.3;
theta_y = M_.params(14);
M_.params(9) = 1;
Ass = M_.params(9);
M_.params(7) = 0.75;
rhoA = M_.params(7);
M_.params(8) = 0.75;
rhoG = M_.params(8);
M_.params(15) = 0.75;
rhoMS = M_.params(15);
M_.params(19) = 0.999;
rhoPS = M_.params(19);
M_.params(20) = 0.999;
rhoIS = M_.params(20);
M_.params(21) = 1;
sigma_A = M_.params(21);
M_.params(22) = 1;
sigma_G = M_.params(22);
M_.params(23) = 1;
sigma_MS = M_.params(23);
M_.params(24) = 1;
sigma_M = M_.params(24);
M_.params(25) = 1;
sigma_PS = M_.params(25);
M_.params(26) = 1;
sigma_IS = M_.params(26);
M_.params(16) = 0.7;
chi = M_.params(16);
M_.params(17) = 0.5;
gammap = M_.params(17);
M_.params(11) = 0.75;
xi = M_.params(11);
M_.params(2) = 7;
zzeta = M_.params(2);
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(5, 5) = (M_.params(26))^2;
M_.Sigma_e(6, 6) = (M_.params(25))^2;
oo_.dr.eigval = check(M_,options_,oo_);
options_.TeX = true;
options_.irf = 40;
options_.order = 1;
options_.graph_format = {'fig'};
var_list_ = {'YY';'CC';'II';'HH';'WW';'RR';'ERER';'QQ';'RnRn';'PIEPIE'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
write_latex_definitions;
write_latex_parameter_table;
collect_latex_files;


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'NK_moreShocks_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_moreShocks_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_moreShocks_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_moreShocks_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_moreShocks_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_moreShocks_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NK_moreShocks_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
