%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'NKlinear';
M_.dynare_version = '5.0';
oo_.dynare_version = '5.0';
options_.dynare_version = '5.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'epsA'};
M_.exo_names_tex(1) = {'{\epsilon^{A}}'};
M_.exo_names_long(1) = {'Labour augmenting shock'};
M_.exo_names(2) = {'epsG'};
M_.exo_names_tex(2) = {'{\epsilon^{G}}'};
M_.exo_names_long(2) = {'Government spending shock'};
M_.exo_names(3) = {'epsMS'};
M_.exo_names_tex(3) = {'{\epsilon^{MS}}'};
M_.exo_names_long(3) = {'Mark-up shock'};
M_.exo_names(4) = {'epsM'};
M_.exo_names_tex(4) = {'{\epsilon^{M}}'};
M_.exo_names_long(4) = {'Monetary policy shock'};
M_.endo_names = cell(32,1);
M_.endo_names_tex = cell(32,1);
M_.endo_names_long = cell(32,1);
M_.endo_names(1) = {'UC'};
M_.endo_names_tex(1) = {'UC'};
M_.endo_names_long(1) = {'Marginal utility of consumption'};
M_.endo_names(2) = {'UH'};
M_.endo_names_tex(2) = {'UH'};
M_.endo_names_long(2) = {'Marginal utility of labour'};
M_.endo_names(3) = {'R'};
M_.endo_names_tex(3) = {'R'};
M_.endo_names_long(3) = {'Risk free interest rate'};
M_.endo_names(4) = {'ER'};
M_.endo_names_tex(4) = {'E(R)'};
M_.endo_names_long(4) = {'Ex-post real interest rate'};
M_.endo_names(5) = {'W'};
M_.endo_names_tex(5) = {'W'};
M_.endo_names_long(5) = {'Real wage'};
M_.endo_names(6) = {'H'};
M_.endo_names_tex(6) = {'H'};
M_.endo_names_long(6) = {'Hours'};
M_.endo_names(7) = {'Y'};
M_.endo_names_tex(7) = {'Y'};
M_.endo_names_long(7) = {'Output'};
M_.endo_names(8) = {'K'};
M_.endo_names_tex(8) = {'K'};
M_.endo_names_long(8) = {'Capital stock'};
M_.endo_names(9) = {'I'};
M_.endo_names_tex(9) = {'I'};
M_.endo_names_long(9) = {'Investment'};
M_.endo_names(10) = {'tax'};
M_.endo_names_tex(10) = {'Tax'};
M_.endo_names_long(10) = {'Taxes'};
M_.endo_names(11) = {'A'};
M_.endo_names_tex(11) = {'A'};
M_.endo_names_long(11) = {'Production technology'};
M_.endo_names(12) = {'G'};
M_.endo_names_tex(12) = {'G'};
M_.endo_names_long(12) = {'Government spending'};
M_.endo_names(13) = {'C'};
M_.endo_names_tex(13) = {'C'};
M_.endo_names_long(13) = {'Consumption'};
M_.endo_names(14) = {'Q'};
M_.endo_names_tex(14) = {'Q'};
M_.endo_names_long(14) = {'Tobin Q'};
M_.endo_names(15) = {'X'};
M_.endo_names_tex(15) = {'X'};
M_.endo_names_long(15) = {'Gross growth rate of investment'};
M_.endo_names(16) = {'PIE'};
M_.endo_names_tex(16) = {'Pi'};
M_.endo_names_long(16) = {'Inflation'};
M_.endo_names(17) = {'MC'};
M_.endo_names_tex(17) = {'MC'};
M_.endo_names_long(17) = {'Real marginal costs'};
M_.endo_names(18) = {'Rn'};
M_.endo_names_tex(18) = {'Rn'};
M_.endo_names_long(18) = {'Nominal interest rate'};
M_.endo_names(19) = {'UCF'};
M_.endo_names_tex(19) = {'UCF'};
M_.endo_names_long(19) = {'Marginal utility of consumption - flexible prices'};
M_.endo_names(20) = {'UHF'};
M_.endo_names_tex(20) = {'ULF'};
M_.endo_names_long(20) = {'Marginal utility of labour - flexible prices'};
M_.endo_names(21) = {'RF'};
M_.endo_names_tex(21) = {'RF'};
M_.endo_names_long(21) = {'Risk free interest rate - flexible prices'};
M_.endo_names(22) = {'HF'};
M_.endo_names_tex(22) = {'HF'};
M_.endo_names_long(22) = {'Hours - flxible prices'};
M_.endo_names(23) = {'YF'};
M_.endo_names_tex(23) = {'YF'};
M_.endo_names_long(23) = {'Output - flxible prices'};
M_.endo_names(24) = {'KF'};
M_.endo_names_tex(24) = {'KF'};
M_.endo_names_long(24) = {'Capital stock - flxible prices'};
M_.endo_names(25) = {'IF'};
M_.endo_names_tex(25) = {'IF'};
M_.endo_names_long(25) = {'Investment - flxible prices'};
M_.endo_names(26) = {'GF'};
M_.endo_names_tex(26) = {'GF'};
M_.endo_names_long(26) = {'Government spending - flexible prices'};
M_.endo_names(27) = {'WF'};
M_.endo_names_tex(27) = {'WF'};
M_.endo_names_long(27) = {'Real wage - flxible prices'};
M_.endo_names(28) = {'CF'};
M_.endo_names_tex(28) = {'CF'};
M_.endo_names_long(28) = {'Consumption - flxible prices'};
M_.endo_names(29) = {'QF'};
M_.endo_names_tex(29) = {'QF'};
M_.endo_names_long(29) = {'Tobin Q'};
M_.endo_names(30) = {'XF'};
M_.endo_names_tex(30) = {'XF'};
M_.endo_names_long(30) = {'Gross growth rate of investment'};
M_.endo_names(31) = {'taxF'};
M_.endo_names_tex(31) = {'TaxF'};
M_.endo_names_long(31) = {'Taxes - flxible prices'};
M_.endo_names(32) = {'MS'};
M_.endo_names_tex(32) = {'MS'};
M_.endo_names_long(32) = {'Mark-up shock'};
M_.endo_partitions = struct();
M_.param_names = cell(27,1);
M_.param_names_tex = cell(27,1);
M_.param_names_long = cell(27,1);
M_.param_names(1) = {'zzeta'};
M_.param_names_tex(1) = {'{\zeta}'};
M_.param_names_long(1) = {'Elasticity of substitution across products'};
M_.param_names(2) = {'alp'};
M_.param_names_tex(2) = {'{\alpha}'};
M_.param_names_long(2) = {'Labour share'};
M_.param_names(3) = {'betta'};
M_.param_names_tex(3) = {'{\beta}'};
M_.param_names_long(3) = {'Discount factor'};
M_.param_names(4) = {'delta'};
M_.param_names_tex(4) = {'{\delta}'};
M_.param_names_long(4) = {'Capital depreciation'};
M_.param_names(5) = {'sigma_c'};
M_.param_names_tex(5) = {'{\sigma_{C}}'};
M_.param_names_long(5) = {'Inverse of the elasticity of substitution'};
M_.param_names(6) = {'varrho'};
M_.param_names_tex(6) = {'{\varrho}'};
M_.param_names_long(6) = {'Weight on Leisure in utility'};
M_.param_names(7) = {'rhoA'};
M_.param_names_tex(7) = {'{\rho_{A}}'};
M_.param_names_long(7) = {'Persistence of labour augmentig shock'};
M_.param_names(8) = {'rhoG'};
M_.param_names_tex(8) = {'{\rho_{G}}'};
M_.param_names_long(8) = {'Persistence of government spending shock'};
M_.param_names(9) = {'rhoMS'};
M_.param_names_tex(9) = {'{\rho_{MS}}'};
M_.param_names_long(9) = {'Persistence of mark-up shock'};
M_.param_names(10) = {'Ass'};
M_.param_names_tex(10) = {'{\bar{A}}'};
M_.param_names_long(10) = {'Labour technology in steady state'};
M_.param_names(11) = {'phiX'};
M_.param_names_tex(11) = {'{\phi_{X}}'};
M_.param_names_long(11) = {'Smoothing parameter of investment adjustment costs'};
M_.param_names(12) = {'xi'};
M_.param_names_tex(12) = {'{\xi}'};
M_.param_names_long(12) = {'Calvo parameter'};
M_.param_names(13) = {'chi'};
M_.param_names_tex(13) = {'{\chi}'};
M_.param_names_long(13) = {'habits persistence'};
M_.param_names(14) = {'gammap'};
M_.param_names_tex(14) = {'{\gamma^{p}}'};
M_.param_names_long(14) = {'degree of indexation'};
M_.param_names(15) = {'rho_r'};
M_.param_names_tex(15) = {'{\rho_{R}}'};
M_.param_names_long(15) = {'Interest rate smoothing parameter'};
M_.param_names(16) = {'theta_pie'};
M_.param_names_tex(16) = {'\theta^{\pi}'};
M_.param_names_long(16) = {'Taylor rule parameter for inflation'};
M_.param_names(17) = {'theta_y'};
M_.param_names_tex(17) = {'\theta^{y}'};
M_.param_names_long(17) = {'Taylor rule parameter for output'};
M_.param_names(18) = {'hss'};
M_.param_names_tex(18) = {'{\bar{H}}'};
M_.param_names_long(18) = {'Hours in steady state'};
M_.param_names(19) = {'Rss'};
M_.param_names_tex(19) = {'{\bar{R}}'};
M_.param_names_long(19) = {'Risk free interest rate in steady state - flexible prices'};
M_.param_names(20) = {'hfss'};
M_.param_names_tex(20) = {'{\bar{H}}'};
M_.param_names_long(20) = {'Hours in steady state - flexible prices'};
M_.param_names(21) = {'Rfss'};
M_.param_names_tex(21) = {'{\bar{RF}}'};
M_.param_names_long(21) = {'Risk free interest rate in steady state - flexible prices'};
M_.param_names(22) = {'PWPss'};
M_.param_names_tex(22) = {'{{\bar{P}}^{W}}'};
M_.param_names_long(22) = {'Intermediate price in steady state'};
M_.param_names(23) = {'cy'};
M_.param_names_tex(23) = {'{cy}'};
M_.param_names_long(23) = {'Consumption output ratio in steady state'};
M_.param_names(24) = {'iy'};
M_.param_names_tex(24) = {'{iy}'};
M_.param_names_long(24) = {'Investment output ratio in steady state'};
M_.param_names(25) = {'gy'};
M_.param_names_tex(25) = {'{gy}'};
M_.param_names_long(25) = {'Government spending output ratio in steady state - flexible prices'};
M_.param_names(26) = {'iyf'};
M_.param_names_tex(26) = {'{iyf}'};
M_.param_names_long(26) = {'Investment output ratio in steady state'};
M_.param_names(27) = {'cyf'};
M_.param_names_tex(27) = {'{cyf}'};
M_.param_names_long(27) = {'Consumption output ratio in steady state - flexible prices'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 32;
M_.param_nbr = 27;
M_.orig_endo_nbr = 32;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 32;
M_.eq_nbr = 32;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 13 45;
 0 14 0;
 0 15 46;
 0 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 1 20 0;
 2 21 47;
 0 22 0;
 3 23 0;
 4 24 0;
 5 25 0;
 0 26 0;
 0 27 48;
 6 28 49;
 0 29 0;
 7 30 0;
 0 31 50;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 8 36 0;
 9 37 51;
 10 38 0;
 0 39 0;
 11 40 0;
 0 41 0;
 0 42 52;
 0 43 0;
 12 44 0;]';
M_.nstatic = 15;
M_.nfwrd   = 5;
M_.npred   = 9;
M_.nboth   = 3;
M_.nsfwrd   = 8;
M_.nspred   = 12;
M_.ndynamic   = 17;
M_.dynamic_tmp_nbr = [2; 0; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Marginal Utility of Consumption (with external habits) 1 - flexible prices' ;
  2 , 'name' , 'Marginal Utility of Consumption (with external habits) 2 - flexible prices' ;
  3 , 'name' , 'Euler equation - flexible prices' ;
  4 , 'name' , 'Labour supply foc - flexible prices' ;
  5 , 'name' , 'Prodution function- flexible prices' ;
  6 , 'name' , 'Wholesale firms FOC for labour- flexible prices' ;
  7 , 'name' , 'Resource constraint- flexible prices' ;
  8 , 'name' , 'Resource constraint- flexible prices' ;
  9 , 'name' , 'Tobin s Q 1- flexible prices' ;
  10 , 'name' , 'Tobin s Q 2- flexible prices' ;
  11 , 'name' , 'Investment- flexible prices' ;
  12 , 'name' , 'Balance budget constraint 1 - flexible prices' ;
  13 , 'name' , 'Balance budget constraint 2 - flexible prices' ;
  14 , 'name' , 'Marginal Utility of Consumption (with external habits)' ;
  15 , 'name' , 'Marginal Utility of Consumption (with external habits) 2' ;
  16 , 'name' , 'Euler equation' ;
  17 , 'name' , 'Labour supply foc' ;
  18 , 'name' , 'Prodution function' ;
  19 , 'name' , 'Wholesale firms FOC for labou' ;
  20 , 'name' , 'Resource constraint' ;
  21 , 'name' , 'Capital law of motion' ;
  22 , 'name' , 'Tobin s Q 1' ;
  23 , 'name' , 'Tobin s Q 2' ;
  24 , 'name' , 'Investments' ;
  25 , 'name' , 'Balanced budget constraint' ;
  26 , 'name' , 'Phillips Curve' ;
  27 , 'name' , 'Taylor rule - implementable rule (relative to ss)' ;
  28 , 'name' , 'Real Interest Rate' ;
  29 , 'name' , 'Real Ex-Post Interest Rate' ;
  30 , 'name' , 'Technology shock process' ;
  31 , 'name' , 'Government spending shock process' ;
  32 , 'name' , 'Markup shock process' ;
};
M_.mapping.UC.eqidx = [14 15 16 17 ];
M_.mapping.UH.eqidx = [16 17 ];
M_.mapping.R.eqidx = [15 23 28 ];
M_.mapping.ER.eqidx = [29 ];
M_.mapping.W.eqidx = [17 19 25 ];
M_.mapping.H.eqidx = [14 16 18 19 25 ];
M_.mapping.Y.eqidx = [18 19 20 22 27 ];
M_.mapping.K.eqidx = [18 21 22 ];
M_.mapping.I.eqidx = [20 21 24 ];
M_.mapping.tax.eqidx = [25 ];
M_.mapping.A.eqidx = [5 18 30 ];
M_.mapping.G.eqidx = [20 25 31 ];
M_.mapping.C.eqidx = [14 16 20 ];
M_.mapping.Q.eqidx = [22 23 24 ];
M_.mapping.X.eqidx = [22 23 ];
M_.mapping.PIE.eqidx = [26 27 28 29 ];
M_.mapping.MC.eqidx = [19 22 26 ];
M_.mapping.Rn.eqidx = [27 28 29 ];
M_.mapping.UCF.eqidx = [1 2 3 4 ];
M_.mapping.UHF.eqidx = [3 4 ];
M_.mapping.RF.eqidx = [2 10 ];
M_.mapping.HF.eqidx = [1 3 5 6 12 ];
M_.mapping.YF.eqidx = [5 6 7 9 ];
M_.mapping.KF.eqidx = [5 8 9 ];
M_.mapping.IF.eqidx = [7 8 11 ];
M_.mapping.GF.eqidx = [7 12 13 ];
M_.mapping.WF.eqidx = [4 6 12 ];
M_.mapping.CF.eqidx = [1 3 7 ];
M_.mapping.QF.eqidx = [9 10 11 ];
M_.mapping.XF.eqidx = [9 10 ];
M_.mapping.taxF.eqidx = [12 ];
M_.mapping.MS.eqidx = [26 32 ];
M_.mapping.epsA.eqidx = [30 ];
M_.mapping.epsG.eqidx = [13 31 ];
M_.mapping.epsMS.eqidx = [32 ];
M_.mapping.epsM.eqidx = [27 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [8 9 11 12 13 16 18 24 25 26 28 32 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(32, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(27, 1);
M_.endo_trends = struct('deflator', cell(32, 1), 'log_deflator', cell(32, 1), 'growth_factor', cell(32, 1), 'log_growth_factor', cell(32, 1));
M_.NNZDerivatives = [118; 0; -1; ];
M_.static_tmp_nbr = [2; 1; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
close all;
M_.params(14) = 0.5;
gammap = M_.params(14);
M_.params(13) = 0.7;
chi = M_.params(13);
M_.params(18) = 0.35;
hss = M_.params(18);
M_.params(11) = 2.0;
phiX = M_.params(11);
M_.params(25) = 0.2;
gy = M_.params(25);
M_.params(2) = 0.70;
alp = M_.params(2);
M_.params(1) = 7.0;
zzeta = M_.params(1);
M_.params(3) = 0.99;
betta = M_.params(3);
M_.params(4) = 0.0250;
delta = M_.params(4);
M_.params(5) = 2.0;
sigma_c = M_.params(5);
M_.params(12) = 0.75;
xi = M_.params(12);
M_.params(15) = 0.7;
rho_r = M_.params(15);
M_.params(16) = 1.5;
theta_pie = M_.params(16);
M_.params(17) = 0.3;
theta_y = M_.params(17);
M_.params(10) = 1;
Ass = M_.params(10);
M_.params(7) = 0.75;
rhoA = M_.params(7);
M_.params(8) = 0.75;
rhoG = M_.params(8);
M_.params(9) = 0.75;
rhoMS = M_.params(9);
M_.params(13) = 0;
chi = M_.params(13);
M_.params(14) = 0.99;
gammap = M_.params(14);
M_.params(20) = M_.params(18);
hfss = M_.params(20);
M_.params(19) = 1.0/M_.params(3);
Rss = M_.params(19);
M_.params(21) = M_.params(19);
Rfss = M_.params(21);
M_.params(22) = 1-1/M_.params(1);
PWPss = M_.params(22);
M_.params(24) = M_.params(22)*(1-M_.params(2))*M_.params(4)/(M_.params(4)+M_.params(19)-1);
iy = M_.params(24);
M_.params(23) = 1-M_.params(24)-M_.params(25);
cy = M_.params(23);
M_.params(26) = (1-M_.params(2))*M_.params(22)*M_.params(4)/(M_.params(4)+M_.params(21)-1);
iyf = M_.params(26);
M_.params(27) = 1-M_.params(26)-M_.params(25);
cyf = M_.params(27);
M_.params(6) = (1-M_.params(18))/(1+M_.params(18)*(M_.params(23)*(1-M_.params(13))/(M_.params(22)*M_.params(2))-1));
varrho = M_.params(6);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
M_.Sigma_e(2, 2) = (1)^2;
M_.Sigma_e(3, 3) = (1)^2;
M_.Sigma_e(4, 4) = (1)^2;
options_.irf = 40;
options_.order = 1;
options_.graph_format = {'fig'};
var_list_ = {'Y';'C';'I';'H';'W';'R';'ER';'Q';'Rn';'PIE'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
collect_latex_files;


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'NKlinear_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NKlinear_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NKlinear_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NKlinear_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NKlinear_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NKlinear_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'NKlinear_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
